### PR TITLE
Added help. Changed ArrayList to List

### PR DESCRIPTION
**Pull request by lodenrogue**

### CODE REVIEW

**Comment by lodenrogue** [comment]
Output looks something like this:

```
-i, --input-files             XMLpaths
-s, --schema-path             XSDpath
-t, --concurrency-limit       Filethreadlimit
-r, --restructure-type        Restructure mode
-c, --conformity              Conformitycheck mode
-y, --verify                  Verify mode
-v, --verbose                 Verbose mode
-d, --debug                   Debug mode
-h, --help                    Help
```

**Comment by lodenrogue** [comment]
We need to decide what the descriptions should be for these. I'm just using the full name of the param for now

**Comment by Nyuu** [comment]
Nyuu!
Sorry for replying so late, but my main job has me have very little time currently to do anything ^^"
This project is primarily for me to learn to use git/github and also to try a new style of coding (so some decisions to write some code from scratch are intentional, like the command line parsin functionality. I simply did not like any solution i found).
I requested what i wanted specifically in my issue and did not want anything more because it was meant to be a simple exercise  for me to write issues, and maybe merge pull requests.
I do not want to merge your PR for these reasons:
You changed files where you removed imports. I think they were probably marked by your IDE as "unused" or "unecessary" due to being in the same package, but in one of the classes i wrote that this is intentionally, because i am trying a new, more readable approach to code and the imports should give a first glance about what code parts are used ^^
You changed the ArrayList to List. I do not know why, if you want, could you elaborate? I used the type that i knew would do it's specific jobs and i did not need primitives support which would be the only reason for me to think of currently to use List instead of ArrayList.
Your "Helper" class is not following any of my design nor naming schemes :c and again, adds functionality that i do not yet want. The approach is good though and i liked it ^_^

The problems probably arose because of me not specifying the personal goals for this project nor having a contribute.md as i learned recently ^^"
As i wrote, i am still new to this git/github stuff and usually code different languages and in projects handeled totally different, not from an OOP approach.

Nyuu <3

**Comment by lodenrogue** [comment]
Look into Liskov substitution principle and other SOLID principles. You should be programming to interfaces not implementations. List is the interface and ArrayList is the implementation.

```
You changed files where you removed imports. I think they were probably marked by your IDE as "unused" or "unecessary" due to being in the same package, but in one of the classes i wrote that this is intentionally, because i am trying a new, more readable approach to code and the imports should give a first glance about what code parts are used
```

13 years as Java engineering and no one reads the imports. Especially when using an IDE. They're not going to start now.

```
I requested what i wanted specifically in my issue and did not want anything more because it was meant to be a simple exercise for me to write issues, and maybe merge pull requests.
```

This should have been specified when I asked how I can help. No worries.

```
Your "Helper" class is not following any of my design nor naming schemes :c and again, adds functionality that i do not yet want.
```

The Helper class does exactly what was asked for and follows the same naming and design pattern as the other classes. It prints the help information in the standard Unix POSIX -h format

**Pull request closed without merging**
